### ISSUE TITLE
Comparative data

### ISSUE THREAD

**Issue by jd-foster** [jump-dev/JuMPPaperBenchmarks#3]
```
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cascadelake)

  [60bf3e95] GLPK v1.0.1
  [2e9cd046] Gurobi v0.11.2 `https://github.com/jump-dev/Gurobi.jl.git#master`
  [87dc4568] HiGHS v1.1.3
  [b6b21f68] Ipopt v1.0.2
  [4076af6c] JuMP v1.0.0
  [b8f27783] MathOptInterface v1.2.0 `https://github.com/jump-dev/MathOptInterface.jl.git#master`
  [9b87118b] PackageCompiler v2.0.5
  [8f399da3] Libdl
```

`benchmarks.csv`: (not really a CSV though 😋)
|type | case-n | num_var | run_time|
| --- | --- | --- | --- |
|direct|fac-25|67651|1|
|direct|fac-50|520301|6|
|direct|fac-75|1732951|22|
|direct|fac-100|4080601|58|
|default|fac-25|67651|1|
|default|fac-50|520301|6|
|default|fac-75|1732951|27|
|default|fac-100|4080601|63|
|direct|lqcp-500|251501|3|
|direct|lqcp-1000|1003001|14|
|direct|lqcp-1500|2254501|42|
|direct|lqcp-2000|4006001|98|
|default|lqcp-500|251501|6|
|default|lqcp-1000|1003001|14|
|default|lqcp-1500|2254501|33|
|default|lqcp-2000|4006001|58|

**Comment by odow** [comment]
> direct | lqcp-2000 | 4006001 | 98

What happened here? Did you run out of RAM or something?

Here were my results:
![image](https://user-images.githubusercontent.com/8177701/166855576-b1d43e6f-f6b7-47f4-ae88-88ffad4f0e2d.png)

**Comment by jd-foster** [comment]
No, plenty of RAM available. It's doing a network license check, so maybe latency on the request?
Otherwise, direct log was
```
Barrier performed 0 iterations in 5.36 seconds (0.01 work units)
Time limit reached
```
compared to the default log
```
Barrier performed 0 iterations in 5.36 seconds (0.01 work units)
Time limit reached
```
